In [ ]:
import pandas as pd
import numpy as np

In [ ]:
data_preprocessed = pd.read_csv('/content/drive/MyDrive/Processed_Absent.csv')
data_preprocessed.head(20)

Reason_1  Reason_2  Reason_3  Reason_4  Months  Day of Week  \
0          0         0         0         1       7            1   
1          0         0         0         0       7            1   
2          0         0         0         1       7            2   
3          1         0         0         0       7            3   
4          0         0         0         1       7            3   
5          0         0         0         1       7            4   
6          0         0         0         1       7            4   
7          0         0         0         1       7            4   
8          0         0         1         0       7            0   
9          0         0         0         1       7            0   
10         1         0         0         0       7            0   
11         1         0         0         0       7            1   
12         1         0         0         0       7            2   
13         1         0         0         0       7            2   
14         0         0         0         1       7            2   
15         1         0         0         0       7            4   
16         0         0         0         1       7            4   
17         0         0         1         0       7            0   
18         1         0         0         0       7            3   
19         0         0         0         1       8            2   

    Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                      289                36   33                  239.554   
1                      118                13   50                  239.554   
2                      179                51   38                  239.554   
3                      279                 5   39                  239.554   
4                      289                36   33                  239.554   
5                      179                51   38                  239.554   
6                      361                52   28                  239.554   
7                      260                50   36                  239.554   
8                      155                12   34                  239.554   
9                      235                11   37                  239.554   
10                     260                50   36                  239.554   
11                     260                50   36                  239.554   
12                     260                50   36                  239.554   
13                     179                51   38                  239.554   
14                     179                51   38                  239.554   
15                     246                25   41                  239.554   
16                     179                51   38                  239.554   
17                     179                51   38                  239.554   
18                     189                29   33                  239.554   
19                     248                25   47                  205.917   

    Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  
0                30          0         2     1                          4  
1                31          0         1     0                          0  
2                31          0         0     0                          2  
3                24          0         2     0                          4  
4                30          0         2     1                          2  
5                31          0         0     0                          2  
6                27          0         1     4                          8  
7                23          0         4     0                          4  
8                25          0         2     0                         40  
9                29          1         1     1                          8  
10               23          0         4     0                          8  
11               23          0         4     

In [ ]:
# Create Target
median_value = data_preprocessed['Absenteeism Time in Hours'].median()
median_value

3.0

In [ ]:
target = np.where(data_preprocessed['Absenteeism Time in Hours']>median_value,1,0 )
target

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [ ]:
target.shape

(700,)

In [ ]:
data_preprocessed['Excessive absence'] = target
data_preprocessed.head()

Reason_1  Reason_2  Reason_3  Reason_4  Months  Day of Week  \
0         0         0         0         1       7            1   
1         0         0         0         0       7            1   
2         0         0         0         1       7            2   
3         1         0         0         0       7            3   
4         0         0         0         1       7            3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  \
0               30          0         2     1                          4   
1               31          0         1     0                          0   
2               31          0         0     0                          2   
3               24          0         2     0                          4   
4               30          0         2     1                          2   

   Excessive absence  
0                  1  
1                  0  
2                  0  
3                  1  
4                  0

In [ ]:
df_target = data_preprocessed.drop(['Absenteeism Time in Hours'],axis=1)
df_target.head()
df_target.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Months',
       'Day of Week', 'Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets', 'Excessive absence'], dtype=object)

In [ ]:
# Select Inputs
df_target.columns = ['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Months',
       'Day of Week', 'Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets', 'Excessive absence']


In [ ]:
column_reorder = ['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4','Education','Months',
       'Day of Week', 'Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index','Children', 'Pets', 'Excessive absence']

In [ ]:
df_target = df_target[column_reorder]
df_target.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Education',
       'Months', 'Day of Week', 'Transportation Expense',
       'Distance to Work', 'Age', 'Daily Work Load Average',
       'Body Mass Index', 'Children', 'Pets', 'Excessive absence'],
      dtype=object)

In [ ]:
unscaled_inputs = df_target.iloc[:,5:-1]
unscaled_inputs.head()

Months  Day of Week  Transportation Expense  Distance to Work  Age  \
0       7            1                     289                36   33   
1       7            1                     118                13   50   
2       7            2                     179                51   38   
3       7            3                     279                 5   39   
4       7            3                     289                36   33   

   Daily Work Load Average  Body Mass Index  Children  Pets  
0                  239.554               30         2     1  
1                  239.554               31         1     0  
2                  239.554               31         0     0  
3                  239.554               24         2     0  
4                  239.554               30         2     1

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(unscaled_inputs)

StandardScaler()

In [ ]:
scaled_inputs = scaler.transform(unscaled_inputs)
scaled_inputs

array([[ 0.18272635, -0.68370352,  1.00584437, ...,  0.76743118,
         0.88046927,  0.26848661],
       [ 0.18272635, -0.68370352, -1.57468098, ...,  1.00263338,
        -0.01928035, -0.58968976],
       [ 0.18272635, -0.00772546, -0.6541427 , ...,  1.00263338,
        -0.91902997, -0.58968976],
       ...,
       [-0.3882935 ,  0.66825259,  1.62456682, ..., -0.40857982,
        -0.91902997, -0.58968976],
       [-0.3882935 ,  0.66825259,  0.19094163, ..., -0.40857982,
        -0.91902997, -0.58968976],
       [-0.3882935 ,  0.66825259,  1.03602595, ..., -0.40857982,
        -0.01928035,  0.26848661]])

In [ ]:
df_target.iloc[:,5:-1] = scaled_inputs
df_target.head(20)

Reason_1  Reason_2  Reason_3  Reason_4  Education    Months  Day of Week  \
0          0         0         0         1          0  0.182726    -0.683704   
1          0         0         0         0          0  0.182726    -0.683704   
2          0         0         0         1          0  0.182726    -0.007725   
3          1         0         0         0          0  0.182726     0.668253   
4          0         0         0         1          0  0.182726     0.668253   
5          0         0         0         1          0  0.182726     1.344231   
6          0         0         0         1          0  0.182726     1.344231   
7          0         0         0         1          0  0.182726     1.344231   
8          0         0         1         0          0  0.182726    -1.359682   
9          0         0         0         1          1  0.182726    -1.359682   
10         1         0         0         0          0  0.182726    -1.359682   
11         1         0         0         0          0  0.182726    -0.683704   
12         1         0         0         0          0  0.182726    -0.007725   
13         1         0         0         0          0  0.182726    -0.007725   
14         0         0         0         1          0  0.182726    -0.007725   
15         1         0         0         0          0  0.182726     1.344231   
16         0         0         0         1          0  0.182726     1.344231   
17         0         0         1         0          0  0.182726    -1.359682   
18         1         0         0         0          0  0.182726     0.668253   
19         0         0         0         1          0  0.468236    -0.007725   

    Transportation Expense  Distance to Work       Age  \
0                 1.005844          0.412816 -0.536062   
1                -1.574681         -1.141882  2.130803   
2                -0.654143          1.426749  0.248310   
3                 0.854936         -1.682647  0.405184   
4                 1.005844          0.412816 -0.536062   
5                -0.654143          1.426749  0.248310   
6                 2.092381          1.494345 -1.320435   
7                 0.568211          1.359154 -0.065439   
8                -1.016322         -1.209478 -0.379188   
9                 0.190942         -1.277074  0.091435   
10                0.568211          1.359154 -0.065439   
11                0.568211          1.359154 -0.065439   
12                0.568211          1.359154 -0.065439   
13               -0.654143          1.426749  0.248310   
14               -0.654143          1.426749  0.248310   
15                0.356940         -0.330735  0.718933   
16               -0.654143          1.426749  0.248310   
17               -0.654143          1.426749  0.248310   
18               -0.503235         -0.060353 -0.536062   
19                0.387122         -0.330735  1.660180   

    Daily Work Load Average  Body Mass Index  Children      Pets  \
0                 -0.806331         0.767431  0.880469  0.268487   
1                 -0.806331         1.002633 -0.019280 -0.589690   
2                 -0.806331         1.002633 -0.919030 -0.589690   
3                 -0.806331        -0.643782  0.880469 -0.589690   
4                 -0.806331         0.767431  0.880469  0.268487   
5                 -0.806331         1.002633 -0.919030 -0.589690   
6                 -0.806331         0.061825 -0.019280  2.843016   
7                 -0.806331        -0.878984  2.679969 -0.589690   
8                 -0.806331        -0.408580  0.880469 -0.589690   
9                 -0.806331         0.532229 -0.019280  0.268487   
10                -0.806331        -0.878984  2.679969 -0.589690   
11                -0.806331        -0.878984  2.679969 -0.589690   
12                -0.806331        -0.878984  2.679969 -0.589690   
13                -0.806331         1.002633 -0.919030 -0.589690   
14                -0.806331         1.002633 -0.919030 -0.589690   
15              

In [ ]:
scaled_inputs_all = df_target.iloc[:,:-1]
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(scaled_inputs_all,target,train_size=0.8,random_state=20)

In [ ]:
from sklearn.linear_model import LogisticRegression
reg = LogisticRegression()

In [ ]:
reg.fit(x_train,y_train)

LogisticRegression()

In [ ]:
reg.score(x_train,y_train)

0.775

In [ ]:
# Creating Summary table
reg.coef_,reg.intercept_

(array([[ 2.80096498e+00,  9.34857518e-01,  3.09561645e+00,
          8.56587468e-01, -2.05738037e-01,  1.66248119e-01,
         -8.43703301e-02,  6.12732578e-01, -7.79685996e-03,
         -1.65922708e-01, -1.47005122e-04,  2.71811477e-01,
          3.61989880e-01, -2.85510745e-01]]),
 array([-1.6561092]))

In [ ]:
feature_name = scaled_inputs_all.columns.values

In [ ]:
summary_table = pd.DataFrame(columns = ['Feature_name'],data=feature_name)
summary_table['Coefficients'] = np.transpose(reg.coef_)
summary_table

Feature_name  Coefficients
0                  Reason_1      2.800965
1                  Reason_2      0.934858
2                  Reason_3      3.095616
3                  Reason_4      0.856587
4                 Education     -0.205738
5                    Months      0.166248
6               Day of Week     -0.084370
7    Transportation Expense      0.612733
8          Distance to Work     -0.007797
9                       Age     -0.165923
10  Daily Work Load Average     -0.000147
11          Body Mass Index      0.271811
12                 Children      0.361990
13                     Pets     -0.285511

In [ ]:
summary_table.index = summary_table.index + 1
summary_table.loc[0] = ['Intercept',reg.intercept_[0]]
summary_table = summary_table.sort_index()
summary_table

Feature_name  Coefficients
0                 Intercept     -1.656109
1                  Reason_1      2.800965
2                  Reason_2      0.934858
3                  Reason_3      3.095616
4                  Reason_4      0.856587
5                 Education     -0.205738
6                    Months      0.166248
7               Day of Week     -0.084370
8    Transportation Expense      0.612733
9          Distance to Work     -0.007797
10                      Age     -0.165923
11  Daily Work Load Average     -0.000147
12          Body Mass Index      0.271811
13                 Children      0.361990
14                     Pets     -0.285511

In [ ]:
summary_table['Odds_ratio'] = np.exp(summary_table.Coefficients)
summary_table

Feature_name  Coefficients  Odds_ratio
0                 Intercept     -1.656109    0.190880
1                  Reason_1      2.800965   16.460523
2                  Reason_2      0.934858    2.546851
3                  Reason_3      3.095616   22.100858
4                  Reason_4      0.856587    2.355110
5                 Education     -0.205738    0.814046
6                    Months      0.166248    1.180866
7               Day of Week     -0.084370    0.919091
8    Transportation Expense      0.612733    1.845467
9          Distance to Work     -0.007797    0.992233
10                      Age     -0.165923    0.847112
11  Daily Work Load Average     -0.000147    0.999853
12          Body Mass Index      0.271811    1.312340
13                 Children      0.361990    1.436184
14                     Pets     -0.285511    0.751630

In [ ]:
summary_table.sort_values('Odds_ratio',ascending = False)

Feature_name  Coefficients  Odds_ratio
3                  Reason_3      3.095616   22.100858
1                  Reason_1      2.800965   16.460523
2                  Reason_2      0.934858    2.546851
4                  Reason_4      0.856587    2.355110
8    Transportation Expense      0.612733    1.845467
13                 Children      0.361990    1.436184
12          Body Mass Index      0.271811    1.312340
6                    Months      0.166248    1.180866
11  Daily Work Load Average     -0.000147    0.999853
9          Distance to Work     -0.007797    0.992233
7               Day of Week     -0.084370    0.919091
10                      Age     -0.165923    0.847112
5                 Education     -0.205738    0.814046
14                     Pets     -0.285511    0.751630
0                 Intercept     -1.656109    0.190880

In [ ]:
# Test the data
reg.score(x_test,y_test)

0.7428571428571429

In [ ]:
predicted_probability = reg.predict_proba(x_test)
predicted_probability

array([[0.73838887, 0.26161113],
       [0.60860095, 0.39139905],
       [0.40910176, 0.59089824],
       [0.80489361, 0.19510639],
       [0.0732329 , 0.9267671 ],
       [0.31965834, 0.68034166],
       [0.31302205, 0.68697795],
       [0.13341719, 0.86658281],
       [0.79712508, 0.20287492],
       [0.75274419, 0.24725581],
       [0.48222467, 0.51777533],
       [0.1964133 , 0.8035867 ],
       [0.07857533, 0.92142467],
       [0.70622367, 0.29377633],
       [0.30708515, 0.69291485],
       [0.57055326, 0.42944674],
       [0.54143955, 0.45856045],
       [0.57205946, 0.42794054],
       [0.38194051, 0.61805949],
       [0.04857923, 0.95142077],
       [0.6977753 , 0.3022247 ],
       [0.79578125, 0.20421875],
       [0.3949288 , 0.6050712 ],
       [0.42248618, 0.57751382],
       [0.26634773, 0.73365227],
       [0.75608758, 0.24391242],
       [0.51088279, 0.48911721],
       [0.86807166, 0.13192834],
       [0.20221381, 0.79778619],
       [0.78635626, 0.21364374],
       [0.

In [ ]:
predicted_probability[:,1]

array([0.26161113, 0.39139905, 0.59089824, 0.19510639, 0.9267671 ,
       0.68034166, 0.68697795, 0.86658281, 0.20287492, 0.24725581,
       0.51777533, 0.8035867 , 0.92142467, 0.29377633, 0.69291485,
       0.42944674, 0.45856045, 0.42794054, 0.61805949, 0.95142077,
       0.3022247 , 0.20421875, 0.6050712 , 0.57751382, 0.73365227,
       0.24391242, 0.48911721, 0.13192834, 0.79778619, 0.21364374,
       0.37354833, 0.68671888, 0.68840326, 0.54141425, 0.20421875,
       0.50817528, 0.21068631, 0.74426986, 0.43687316, 0.59038329,
       0.22501874, 0.43474443, 0.21701898, 0.39313905, 0.8143125 ,
       0.57069356, 0.69250264, 0.27274934, 0.20204647, 0.18057868,
       0.59237372, 0.34581089, 0.66771423, 0.28542145, 0.84957431,
       0.47045028, 0.88919506, 0.25614793, 0.31973858, 0.31768456,
       0.72178349, 0.6571659 , 0.31198576, 0.78711296, 0.19846624,
       0.26534346, 0.08192232, 0.23025544, 0.7270172 , 0.33464876,
       0.21066287, 0.29448939, 0.90909748, 0.43911695, 0.61982

In [ ]:
x_test

Reason_1  Reason_2  Reason_3  Reason_4  Education    Months  Day of Week  \
535         0         0         0         1          0  1.324766     1.344231   
281         0         0         0         1          0  0.753746     1.344231   
324         0         0         0         1          0  1.324766    -1.359682   
645         0         0         0         1          0 -0.959313     1.344231   
10          1         0         0         0          0  0.182726    -1.359682   
..        ...       ...       ...       ...        ...       ...          ...   
136         0         0         0         1          0 -1.530333     0.668253   
430         0         0         0         1          0 -0.388293     0.668253   
32          0         0         0         1          1  0.468236     0.668253   
449         0         0         0         1          0 -0.102784    -0.683704   
59          0         0         0         1          0  0.753746     1.344231   

     Transportation Expense  Distance to Work       Age  \
535               -0.654143          1.426749  0.248310   
281                1.036026          0.074838  0.562059   
324                0.190942         -0.668713  1.032682   
645               -0.654143          1.426749  0.248310   
10                 0.568211          1.359154 -0.065439   
..                      ...               ...       ...   
136                1.005844          0.412816 -0.536062   
430                2.092381          1.494345 -1.320435   
32                 0.190942         -1.277074  0.091435   
449                0.356940         -0.330735  0.718933   
59                 0.387122         -0.330735  1.660180   

     Daily Work Load Average  Body Mass Index  Children      Pets  
535                -0.082083         1.002633 -0.919030 -0.589690  
281                 0.560476        -0.408580 -0.019280  0.268487  
324                 0.305783         2.649049 -0.019280 -0.589690  
645                -1.240355         1.002633 -0.919030 -0.589690  
10                 -0.806331        -0.878984  2.679969 -0.589690  
..                       ...              ...       ...       ...  
136                 0.919937         0.767431  0.880469  0.268487  
430                -0.643304         0.061825 -0.019280  2.843016  
32                 -1.647399         0.532229 -0.019280  0.268487  
449                -0.446195        -0.878984 -0.919030 -0.589690  
59                 -0.758273         1.237836  0.880469  0.268487  

[140 rows x 14 columns]

In [ ]:
prediction = reg.predict(x_test)
prediction.shape

(140,)

In [ ]:
x_test.shape

(140, 14)

In [ ]:
Absent_prediction = x_test.copy()
Absent_prediction

Reason_1  Reason_2  Reason_3  Reason_4  Education    Months  Day of Week  \
535         0         0         0         1          0  1.324766     1.344231   
281         0         0         0         1          0  0.753746     1.344231   
324         0         0         0         1          0  1.324766    -1.359682   
645         0         0         0         1          0 -0.959313     1.344231   
10          1         0         0         0          0  0.182726    -1.359682   
..        ...       ...       ...       ...        ...       ...          ...   
136         0         0         0         1          0 -1.530333     0.668253   
430         0         0         0         1          0 -0.388293     0.668253   
32          0         0         0         1          1  0.468236     0.668253   
449         0         0         0         1          0 -0.102784    -0.683704   
59          0         0         0         1          0  0.753746     1.344231   

     Transportation Expense  Distance to Work       Age  \
535               -0.654143          1.426749  0.248310   
281                1.036026          0.074838  0.562059   
324                0.190942         -0.668713  1.032682   
645               -0.654143          1.426749  0.248310   
10                 0.568211          1.359154 -0.065439   
..                      ...               ...       ...   
136                1.005844          0.412816 -0.536062   
430                2.092381          1.494345 -1.320435   
32                 0.190942         -1.277074  0.091435   
449                0.356940         -0.330735  0.718933   
59                 0.387122         -0.330735  1.660180   

     Daily Work Load Average  Body Mass Index  Children      Pets  
535                -0.082083         1.002633 -0.919030 -0.589690  
281                 0.560476        -0.408580 -0.019280  0.268487  
324                 0.305783         2.649049 -0.019280 -0.589690  
645                -1.240355         1.002633 -0.919030 -0.589690  
10                 -0.806331        -0.878984  2.679969 -0.589690  
..                       ...              ...       ...       ...  
136                 0.919937         0.767431  0.880469  0.268487  
430                -0.643304         0.061825 -0.019280  2.843016  
32                 -1.647399         0.532229 -0.019280  0.268487  
449                -0.446195        -0.878984 -0.919030 -0.589690  
59                 -0.758273         1.237836  0.880469  0.268487  

[140 rows x 14 columns]

In [ ]:
Absent_prediction['probability'] = predicted_probability[:,1]
Absent_prediction['prediction'] = prediction
Absent_prediction

Reason_1  Reason_2  Reason_3  Reason_4  Education    Months  Day of Week  \
535         0         0         0         1          0  1.324766     1.344231   
281         0         0         0         1          0  0.753746     1.344231   
324         0         0         0         1          0  1.324766    -1.359682   
645         0         0         0         1          0 -0.959313     1.344231   
10          1         0         0         0          0  0.182726    -1.359682   
..        ...       ...       ...       ...        ...       ...          ...   
136         0         0         0         1          0 -1.530333     0.668253   
430         0         0         0         1          0 -0.388293     0.668253   
32          0         0         0         1          1  0.468236     0.668253   
449         0         0         0         1          0 -0.102784    -0.683704   
59          0         0         0         1          0  0.753746     1.344231   

     Transportation Expense  Distance to Work       Age  \
535               -0.654143          1.426749  0.248310   
281                1.036026          0.074838  0.562059   
324                0.190942         -0.668713  1.032682   
645               -0.654143          1.426749  0.248310   
10                 0.568211          1.359154 -0.065439   
..                      ...               ...       ...   
136                1.005844          0.412816 -0.536062   
430                2.092381          1.494345 -1.320435   
32                 0.190942         -1.277074  0.091435   
449                0.356940         -0.330735  0.718933   
59                 0.387122         -0.330735  1.660180   

     Daily Work Load Average  Body Mass Index  Children      Pets  \
535                -0.082083         1.002633 -0.919030 -0.589690   
281                 0.560476        -0.408580 -0.019280  0.268487   
324                 0.305783         2.649049 -0.019280 -0.589690   
645                -1.240355         1.002633 -0.919030 -0.589690   
10                 -0.806331        -0.878984  2.679969 -0.589690   
..                       ...              ...       ...       ...   
136                 0.919937         0.767431  0.880469  0.268487   
430                -0.643304         0.061825 -0.019280  2.843016   
32                 -1.647399         0.532229 -0.019280  0.268487   
449                -0.446195        -0.878984 -0.919030 -0.589690   
59                 -0.758273         1.237836  0.880469  0.268487   

     probability  prediction  
535     0.261611           0  
281     0.391399           0  
324     0.590898           1  
645     0.195106           0  
10      0.926767           1  
..           ...         ...  
136     0.510561           1  
430     0.442077           0  
32      0.307732           0  
449     0.257292           0  
59      0.439135           0  

[140 rows x 16 columns]

In [ ]:
Absent_prediction.to_csv('/content/drive/MyDrive/Absent_prediction.csv',index=False)